import { ChallengeDefinition } from "../managers/ChallengeManager";

export const CHALLENGES: Record<string, ChallengeDefinition[]> = {
  easy: [
    {
      id: "stone_age_stockpile",
      name: "Stone Age Stockpile (64 Cobblestone)",
      item: "minecraft:cobblestone",
      count: 64,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "lumberjacks_load",
      name: "Lumberjack's Load (32 Logs, any wood)",
      item: "minecraft:oak_log",
      count: 32,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "farmers_bounty",
      name: "Farmer's Bounty (16 Bread)",
      item: "minecraft:bread",
      count: 16,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "miners_first_strike",
      name: "Miner's First Strike (16 Coal)",
      item: "minecraft:coal",
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "wool_gatherer",
      name: "Wool Gatherer (12 Wool, any color)",
      item: "minecraft:white_wool",
      count: 12,
      points: 15,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "hunters_feast",
      name: "Hunter's Feast (16 Cooked Meat, any type)",
      item: "minecraft:cooked_beef",
      count: 16,
      points: 15,
      difficulty: "easy",
      variant: "any",
    },
    { id: "iron_seeker", name: "Iron Seeker", item: "minecraft:iron_ore", count: 8, points: 18, difficulty: "easy" },
    {
      id: "builders_cache",
      name: "Builder's Cache (32 Planks, any wood)",
      item: "minecraft:oak_planks",
      count: 32,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "dirt_digger",
      name: "Dirt Digger (64 Dirt/Grass Blocks)",
      item: "minecraft:dirt",
      count: 64,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "clay_collector",
      name: "Clay Collector (16 Clay Balls)",
      item: "minecraft:clay_ball",
      count: 16,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "sand_hauler",
      name: "Sand Hauler (32 Sand)",
      item: "minecraft:sand",
      count: 32,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "flower_power",
      name: "Flower Power (10 Different Flowers)",
      item: "minecraft:poppy",
      count: 10,
      points: 18,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "gravel_grab",
      name: "Gravel Grab (32 Gravel)",
      item: "minecraft:gravel",
      count: 32,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "bone_collector",
      name: "Bone Collector (8 Bones)",
      item: "minecraft:bone",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "string_theory",
      name: "String Theory (12 String)",
      item: "minecraft:string",
      count: 12,
      points: 18,
      difficulty: "easy",
    },
  ],
  medium: [
    {
      id: "creepers_gift",
      name: "Creeper's Gift (8 Gunpowder)",
      item: "minecraft:gunpowder",
      count: 8,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "endermans_pearls",
      name: "Enderman's Pearls (5 Ender Pearls)",
      item: "minecraft:ender_pearl",
      count: 5,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "spiders_silk",
      name: "Spider's Silk (8 Spider Eyes)",
      item: "minecraft:spider_eye",
      count: 8,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "iron_forged",
      name: "Iron Forged (4 Iron Blocks)",
      item: "minecraft:iron_block",
      count: 4,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "diamond_toolsmith",
      name: "Diamond Toolsmith (1 Diamond Pickaxe)",
      item: "minecraft:diamond_pickaxe",
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "librarians_pride",
      name: "Librarian's Pride (8 Bookshelves)",
      item: "minecraft:bookshelf",
      count: 8,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "redstone_engineer",
      name: "Redstone Engineer (32 Redstone Dust)",
      item: "minecraft:redstone",
      count: 32,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "golden_ingots",
      name: "Golden Ingots (4 Gold Ingots)",
      item: "minecraft:gold_ingot",
      count: 4,
      points: 38,
      difficulty: "medium",
    },
    {
      id: "slime_hunter",
      name: "Slime Hunter (4 Slimeballs)",
      item: "minecraft:slime_ball",
      count: 4,
      points: 42,
      difficulty: "medium",
    },
    {
      id: "enchanters_start",
      name: "Enchanter's Start (1 Enchanting Table)",
      item: "minecraft:enchanting_table",
      count: 1,
      points: 45,
      difficulty: "medium",
    },
    {
      id: "treasure_map",
      name: "Treasure Map (1 Buried Treasure Map)",
      item: "minecraft:filled_map",
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "melon_merchant",
      name: "Melon Merchant (16 Melons)",
      item: "minecraft:melon",
      count: 16,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "pumpkin_patch",
      name: "Pumpkin Patch (8 Carved Pumpkins)",
      item: "minecraft:carved_pumpkin",
      count: 8,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "leather_worker",
      name: "Leather Worker (8 Leather)",
      item: "minecraft:leather",
      count: 8,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "phantom_membrane",
      name: "Phantom Membrane (2 Phantom Membranes)",
      item: "minecraft:phantom_membrane",
      count: 2,
      points: 45,
      difficulty: "medium",
    },
  ],
  hard: [
    {
      id: "enchanted_knowledge",
      name: "Enchanted Knowledge (1 Enchanted Book)",
      item: "minecraft:enchanted_book",
      count: 1,
      points: 55,
      difficulty: "hard",
      variant: "any",
    },
    {
      id: "golden_delicacy",
      name: "Golden Delicacy (1 Golden Apple)",
      item: "minecraft:golden_apple",
      count: 1,
      points: 60,
      difficulty: "hard",
    },
    {
      id: "village_vault",
      name: "Village Vault (8 Emeralds)",
      item: "minecraft:emerald",
      count: 8,
      points: 65,
      difficulty: "hard",
    },
    {
      id: "mob_tamer",
      name: "Mob Tamer (1 Name Tag)",
      item: "minecraft:name_tag",
      count: 1,
      points: 70,
      difficulty: "hard",
    },
    {
      id: "music_disc_hunter",
      name: "Music Disc Hunter (1 Music Disc, any)",
      item: "minecraft:music_disc_cat",
      count: 1,
      points: 65,
      difficulty: "hard",
      variant: "any",
    },
    {
      id: "diamond_fortune",
      name: "Diamond Fortune (3 Diamonds)",
      item: "minecraft:diamond",
      count: 3,
      points: 60,
      difficulty: "hard",
    },
    {
      id: "totem_raid",
      name: "Totem Raid (1 Totem of Undying)",
      item: "minecraft:totem_of_undying",
      count: 1,
      points: 75,
      difficulty: "hard",
    },
    {
      id: "horse_trader",
      name: "Horse Trader (1 Saddle)",
      item: "minecraft:saddle",
      count: 1,
      points: 55,
      difficulty: "hard",
    },
    {
      id: "oceans_heart",
      name: "Ocean's Heart (1 Heart of the Sea)",
      item: "minecraft:heart_of_the_sea",
      count: 1,
      points: 70,
      difficulty: "hard",
    },
    {
      id: "trident_bearer",
      name: "Trident Bearer (1 Trident)",
      item: "minecraft:trident",
      count: 1,
      points: 75,
      difficulty: "hard",
    },
    {
      id: "bell_ringer",
      name: "Bell Ringer (1 Bell)",
      item: "minecraft:bell",
      count: 1,
      points: 50,
      difficulty: "hard",
    },
    {
      id: "nautilus_shell",
      name: "Nautilus Shell (1 Nautilus Shell)",
      item: "minecraft:nautilus_shell",
      count: 1,
      points: 60,
      difficulty: "hard",
    },
  ],
};
