import { MinecraftItemTypes } from "@minecraft/vanilla-data";
import { ChallengeDefinition } from "../types";

export const CHALLENGES: Record<string, ChallengeDefinition[]> = {
  easy: [
    {
      id: "stone_age_stockpile",
      title: "Stone Age Stockpile",
      name: "32 Cobblestone",
      item: MinecraftItemTypes.Cobblestone,
      count: 32,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "lumberjacks_load",
      title: "Lumberjack's Load",
      name: "16 Logs, any wood",
      item: MinecraftItemTypes.OakLog,
      count: 16,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "farmers_bounty",
      title: "Farmer's Bounty",
      name: "8 Bread",
      item: MinecraftItemTypes.Bread,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "miners_first_strike",
      title: "Miner's First Strike",
      name: "8 Coal",
      item: MinecraftItemTypes.Coal,
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "wool_gatherer",
      title: "Wool Gatherer",
      name: "8 Wool, any color",
      item: MinecraftItemTypes.WhiteWool,
      count: 8,
      points: 15,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "hunters_feast",
      title: "Hunter's Feast",
      name: "8 Cooked Meat, any type",
      item: MinecraftItemTypes.CookedBeef,
      count: 8,
      points: 15,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "iron_seeker",
      title: "Iron Seeker",
      name: "4 Iron Ore",
      item: MinecraftItemTypes.IronOre,
      count: 4,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "builders_cache",
      title: "Builder's Cache",
      name: "32 Planks, any wood",
      item: MinecraftItemTypes.OakPlanks,
      count: 32,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "dirt_digger",
      title: "Dirt Digger",
      name: "32 Dirt/Grass Blocks",
      item: MinecraftItemTypes.Dirt,
      count: 32,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "clay_collector",
      title: "Clay Collector",
      name: "8 Clay Balls",
      item: MinecraftItemTypes.ClayBall,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "sand_hauler",
      title: "Sand Hauler",
      name: "16 Sand",
      item: MinecraftItemTypes.Sand,
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "flower_power",
      title: "Flower Power",
      name: "6 Different Flowers",
      item: MinecraftItemTypes.Poppy,
      count: 6,
      points: 18,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "gravel_grab",
      title: "Gravel Grab",
      name: "16 Gravel",
      item: MinecraftItemTypes.Gravel,
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "bone_collector",
      title: "Bone Collector",
      name: "4 Bones",
      item: MinecraftItemTypes.Bone,
      count: 4,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "string_theory",
      title: "String Theory",
      name: "6 String",
      item: MinecraftItemTypes.String,
      count: 6,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "sugar_rush",
      title: "Sugar Rush",
      name: "8 Sugar Cane",
      item: MinecraftItemTypes.SugarCane,
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "cactus_collector",
      title: "Cactus Collector",
      name: "4 Cactus",
      item: MinecraftItemTypes.Cactus,
      count: 4,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "mushroom_hunt",
      title: "Mushroom Hunt",
      name: "6 Mushrooms, any type",
      item: MinecraftItemTypes.RedMushroom,
      count: 6,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "feather_collector",
      title: "Feather Collector",
      name: "6 Feathers",
      item: MinecraftItemTypes.Feather,
      count: 6,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "egg_basket",
      title: "Egg Basket",
      name: "8 Eggs",
      item: MinecraftItemTypes.Egg,
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "flint_finder",
      title: "Flint Finder",
      name: "4 Flint",
      item: MinecraftItemTypes.Flint,
      count: 4,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "snowball_stockpile",
      title: "Snowball Stockpile",
      name: "16 Snowballs",
      item: MinecraftItemTypes.Snowball,
      count: 16,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "apple_orchard",
      title: "Apple Orchard",
      name: "4 Apples",
      item: MinecraftItemTypes.Apple,
      count: 4,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "stick_stack",
      title: "Stick Stack",
      name: "32 Sticks",
      item: MinecraftItemTypes.Stick,
      count: 32,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "torch_lighter",
      title: "Torch Lighter",
      name: "16 Torches",
      item: MinecraftItemTypes.Torch,
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "charcoal_burner",
      title: "Charcoal Burner",
      name: "8 Charcoal",
      item: MinecraftItemTypes.Charcoal,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "kelp_harvest",
      title: "Kelp Harvest",
      name: "16 Kelp",
      item: MinecraftItemTypes.Kelp,
      count: 16,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "bamboo_gatherer",
      title: "Bamboo Gatherer",
      name: "16 Bamboo",
      item: MinecraftItemTypes.Bamboo,
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "paper_maker",
      title: "Paper Maker",
      name: "8 Paper",
      item: MinecraftItemTypes.Paper,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "sapling_collector",
      title: "Sapling Collector",
      name: "4 Saplings, any type",
      item: MinecraftItemTypes.OakSapling,
      count: 4,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "wheat_harvest",
      title: "Wheat Harvest",
      name: "16 Wheat",
      item: MinecraftItemTypes.Wheat,
      count: 16,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "potato_picker",
      title: "Potato Picker",
      name: "8 Potatoes",
      item: MinecraftItemTypes.Potato,
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "carrot_collector",
      title: "Carrot Collector",
      name: "8 Carrots",
      item: MinecraftItemTypes.Carrot,
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "beetroot_gatherer",
      title: "Beetroot Gatherer",
      name: "8 Beetroots",
      item: MinecraftItemTypes.Beetroot,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "pumpkin_harvest",
      title: "Pumpkin Harvest",
      name: "2 Pumpkins",
      item: MinecraftItemTypes.Pumpkin,
      count: 2,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "melon_slice_stack",
      title: "Melon Slice Stack",
      name: "8 Melon Slices",
      item: MinecraftItemTypes.MelonSlice,
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "vine_climber",
      title: "Vine Climber",
      name: "8 Vines",
      item: MinecraftItemTypes.Vine,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "lily_pad_collector",
      title: "Lily Pad Collector",
      name: "4 Lily Pads",
      item: MinecraftItemTypes.Waterlily,
      count: 4,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "sweet_berries",
      title: "Sweet Berries",
      name: "8 Sweet Berries",
      item: MinecraftItemTypes.SweetBerries,
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "glow_berries",
      title: "Glow Berries",
      name: "6 Glow Berries",
      item: MinecraftItemTypes.GlowBerries,
      count: 6,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "crafting_table_maker",
      title: "Crafting Table Maker",
      name: "2 Crafting Tables",
      item: MinecraftItemTypes.CraftingTable,
      count: 2,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "chest_builder",
      title: "Chest Builder",
      name: "2 Chests",
      item: MinecraftItemTypes.Chest,
      count: 2,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "fence_crafter",
      title: "Fence Crafter",
      name: "16 Fences, any wood",
      item: MinecraftItemTypes.OakFence,
      count: 16,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "door_maker",
      title: "Door Maker",
      name: "3 Doors, any wood",
      item: MinecraftItemTypes.AcaciaDoor,
      count: 3,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
  ],
  medium: [
    {
      id: "creepers_gift",
      title: "Creeper's Gift",
      name: "4 Gunpowder",
      item: MinecraftItemTypes.Gunpowder,
      count: 4,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "endermans_pearls",
      title: "Enderman's Pearls",
      name: "3 Ender Pearls",
      item: MinecraftItemTypes.EnderPearl,
      count: 3,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "spiders_silk",
      title: "Spider's Silk",
      name: "4 Spider Eyes",
      item: MinecraftItemTypes.SpiderEye,
      count: 4,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "iron_forged",
      title: "Iron Forged",
      name: "2 Iron Blocks",
      item: MinecraftItemTypes.IronBlock,
      count: 2,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "diamond_toolsmith",
      title: "Diamond Toolsmith",
      name: "1 Diamond Pickaxe",
      item: MinecraftItemTypes.DiamondPickaxe,
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "librarians_pride",
      title: "Librarian's Pride",
      name: "4 Bookshelves",
      item: MinecraftItemTypes.Bookshelf,
      count: 4,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "redstone_engineer",
      title: "Redstone Engineer",
      name: "16 Redstone Dust",
      item: MinecraftItemTypes.Redstone,
      count: 16,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "golden_ingots",
      title: "Golden Ingots",
      name: "2 Gold Ingots",
      item: MinecraftItemTypes.GoldIngot,
      count: 2,
      points: 38,
      difficulty: "medium",
    },
    {
      id: "slime_hunter",
      title: "Slime Hunter",
      name: "2 Slimeballs",
      item: MinecraftItemTypes.SlimeBall,
      count: 2,
      points: 42,
      difficulty: "medium",
    },
    {
      id: "enchanters_start",
      title: "Enchanter's Start",
      name: "1 Enchanting Table",
      item: MinecraftItemTypes.EnchantingTable,
      count: 1,
      points: 45,
      difficulty: "medium",
    },
    {
      id: "treasure_map",
      title: "Treasure Map",
      name: "1 Buried Treasure Map",
      item: MinecraftItemTypes.FilledMap,
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "melon_merchant",
      title: "Melon Merchant",
      name: "8 Melons",
      item: MinecraftItemTypes.MelonBlock,
      count: 8,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "pumpkin_patch",
      title: "Pumpkin Patch",
      name: "4 Carved Pumpkins",
      item: MinecraftItemTypes.CarvedPumpkin,
      count: 4,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "leather_worker",
      title: "Leather Worker",
      name: "4 Leather",
      item: MinecraftItemTypes.Leather,
      count: 4,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "phantom_membrane",
      title: "Phantom Membrane",
      name: "1 Phantom Membrane",
      item: MinecraftItemTypes.PhantomMembrane,
      count: 1,
      points: 45,
      difficulty: "medium",
    },
    {
      id: "cocoa_farmer",
      title: "Cocoa Farmer",
      name: "8 Cocoa Beans",
      item: MinecraftItemTypes.CocoaBeans,
      count: 8,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "ink_sac_collector",
      title: "Ink Sac Collector",
      name: "4 Ink Sacs",
      item: MinecraftItemTypes.InkSac,
      count: 4,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "lapis_miner",
      title: "Lapis Miner",
      name: "8 Lapis Lazuli",
      item: MinecraftItemTypes.LapisLazuli,
      count: 8,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "dye_collection",
      title: "Dye Collection",
      name: "6 Different Dyes",
      item: MinecraftItemTypes.RedDye,
      count: 6,
      points: 35,
      difficulty: "medium",
      variant: "any",
    },
    {
      id: "obsidian_harvest",
      title: "Obsidian Harvest",
      name: "3 Obsidian",
      item: MinecraftItemTypes.Obsidian,
      count: 3,
      points: 42,
      difficulty: "medium",
    },
    {
      id: "arrow_crafter",
      title: "Arrow Crafter",
      name: "16 Arrows",
      item: MinecraftItemTypes.Arrow,
      count: 16,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "prismarine_collector",
      title: "Prismarine Collector",
      name: "8 Prismarine Shards",
      item: MinecraftItemTypes.PrismarineShard,
      count: 8,
      points: 38,
      difficulty: "medium",
    },
    {
      id: "rabbit_foot",
      title: "Rabbit Foot",
      name: "1 Rabbit's Foot",
      item: MinecraftItemTypes.RabbitFoot,
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "brick_maker",
      title: "Brick Maker",
      name: "16 Bricks",
      item: MinecraftItemTypes.Brick,
      count: 16,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "sugar_producer",
      title: "Sugar Producer",
      name: "16 Sugar",
      item: MinecraftItemTypes.Sugar,
      count: 16,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "bowl_crafter",
      title: "Bowl Crafter",
      name: "6 Bowls",
      item: MinecraftItemTypes.Bowl,
      count: 6,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "glass_maker",
      title: "Glass Maker",
      name: "16 Glass",
      item: MinecraftItemTypes.Glass,
      count: 16,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "dried_kelp_producer",
      title: "Dried Kelp Producer",
      name: "16 Dried Kelp",
      item: MinecraftItemTypes.DriedKelp,
      count: 16,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "honey_collector",
      title: "Honey Collector",
      name: "2 Honey Bottles",
      item: MinecraftItemTypes.HoneyBottle,
      count: 2,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "honeycomb_gatherer",
      title: "Honeycomb Gatherer",
      name: "3 Honeycombs",
      item: MinecraftItemTypes.Honeycomb,
      count: 3,
      points: 35,
      difficulty: "medium",
    },
  ],
  hard: [
    {
      id: "enchanted_knowledge",
      title: "Enchanted Knowledge",
      name: "1 Enchanted Book",
      item: MinecraftItemTypes.EnchantedBook,
      count: 1,
      points: 55,
      difficulty: "hard",
    },
    {
      id: "golden_delicacy",
      title: "Golden Delicacy",
      name: "1 Golden Apple",
      item: MinecraftItemTypes.GoldenApple,
      count: 1,
      points: 60,
      difficulty: "hard",
    },
    {
      id: "village_vault",
      title: "Village Vault",
      name: "8 Emeralds",
      item: MinecraftItemTypes.Emerald,
      count: 8,
      points: 65,
      difficulty: "hard",
    },
    {
      id: "mob_tamer",
      title: "Mob Tamer",
      name: "1 Name Tag",
      item: MinecraftItemTypes.NameTag,
      count: 1,
      points: 70,
      difficulty: "hard",
    },
    {
      id: "music_disc_hunter",
      title: "Music Disc Hunter",
      name: "1 Music Disc, any",
      item: MinecraftItemTypes.MusicDiscCat,
      count: 1,
      points: 65,
      difficulty: "hard",
      variant: "any",
    },
    {
      id: "diamond_fortune",
      title: "Diamond Fortune",
      name: "3 Diamonds",
      item: MinecraftItemTypes.Diamond,
      count: 3,
      points: 60,
      difficulty: "hard",
    },
    {
      id: "totem_raid",
      title: "Totem Raid",
      name: "1 Totem of Undying",
      item: MinecraftItemTypes.TotemOfUndying,
      count: 1,
      points: 75,
      difficulty: "hard",
    },
    {
      id: "horse_trader",
      title: "Horse Trader",
      name: "1 Saddle",
      item: MinecraftItemTypes.Saddle,
      count: 1,
      points: 55,
      difficulty: "hard",
    },
    {
      id: "oceans_heart",
      title: "Ocean's Heart",
      name: "1 Heart of the Sea",
      item: MinecraftItemTypes.HeartOfTheSea,
      count: 1,
      points: 70,
      difficulty: "hard",
    },
    {
      id: "trident_bearer",
      title: "Trident Bearer",
      name: "1 Trident",
      item: MinecraftItemTypes.Trident,
      count: 1,
      points: 75,
      difficulty: "hard",
    },
    {
      id: "bell_ringer",
      title: "Bell Ringer",
      name: "1 Bell",
      item: MinecraftItemTypes.Bell,
      count: 1,
      points: 50,
      difficulty: "hard",
    },
    {
      id: "nautilus_shell",
      title: "Nautilus Shell",
      name: "1 Nautilus Shell",
      item: MinecraftItemTypes.NautilusShell,
      count: 1,
      points: 60,
      difficulty: "hard",
    },
  ],
};
