import { ChallengeDefinition } from "../managers/ChallengeManager";

export const CHALLENGES: Record<string, ChallengeDefinition[]> = {
  easy: [
    {
      id: "stone_age_stockpile",
      name: "Stone Age Stockpile (32 Cobblestone)",
      item: "minecraft:cobblestone",
      count: 32,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "lumberjacks_load",
      name: "Lumberjack's Load (16 Logs, any wood)",
      item: "minecraft:oak_log",
      count: 16,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "farmers_bounty",
      name: "Farmer's Bounty (8 Bread)",
      item: "minecraft:bread",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "miners_first_strike",
      name: "Miner's First Strike (8 Coal)",
      item: "minecraft:coal",
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "wool_gatherer",
      name: "Wool Gatherer (8 Wool, any color)",
      item: "minecraft:white_wool",
      count: 8,
      points: 15,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "hunters_feast",
      name: "Hunter's Feast (8 Cooked Meat, any type)",
      item: "minecraft:cooked_beef",
      count: 8,
      points: 15,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "iron_seeker",
      name: "Iron Seeker (4 Iron Ore)",
      item: "minecraft:iron_ore",
      count: 4,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "builders_cache",
      name: "Builder's Cache (32 Planks, any wood)",
      item: "minecraft:oak_planks",
      count: 32,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "dirt_digger",
      name: "Dirt Digger (32 Dirt/Grass Blocks)",
      item: "minecraft:dirt",
      count: 32,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "clay_collector",
      name: "Clay Collector (8 Clay Balls)",
      item: "minecraft:clay_ball",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "sand_hauler",
      name: "Sand Hauler (16 Sand)",
      item: "minecraft:sand",
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "flower_power",
      name: "Flower Power (6 Different Flowers)",
      item: "minecraft:poppy",
      count: 6,
      points: 18,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "gravel_grab",
      name: "Gravel Grab (16 Gravel)",
      item: "minecraft:gravel",
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "bone_collector",
      name: "Bone Collector (4 Bones)",
      item: "minecraft:bone",
      count: 4,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "string_theory",
      name: "String Theory (6 String)",
      item: "minecraft:string",
      count: 6,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "sugar_rush",
      name: "Sugar Rush (8 Sugar Cane)",
      item: "minecraft:sugar_cane",
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "cactus_collector",
      name: "Cactus Collector (4 Cactus)",
      item: "minecraft:cactus",
      count: 4,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "mushroom_hunt",
      name: "Mushroom Hunt (6 Mushrooms, any type)",
      item: "minecraft:red_mushroom",
      count: 6,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "feather_collector",
      name: "Feather Collector (6 Feathers)",
      item: "minecraft:feather",
      count: 6,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "egg_basket",
      name: "Egg Basket (8 Eggs)",
      item: "minecraft:egg",
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "flint_finder",
      name: "Flint Finder (4 Flint)",
      item: "minecraft:flint",
      count: 4,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "snowball_stockpile",
      name: "Snowball Stockpile (16 Snowballs)",
      item: "minecraft:snowball",
      count: 16,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "apple_orchard",
      name: "Apple Orchard (4 Apples)",
      item: "minecraft:apple",
      count: 4,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "stick_stack",
      name: "Stick Stack (32 Sticks)",
      item: "minecraft:stick",
      count: 32,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "torch_lighter",
      name: "Torch Lighter (16 Torches)",
      item: "minecraft:torch",
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "charcoal_burner",
      name: "Charcoal Burner (8 Charcoal)",
      item: "minecraft:charcoal",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "kelp_harvest",
      name: "Kelp Harvest (16 Kelp)",
      item: "minecraft:kelp",
      count: 16,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "bamboo_gatherer",
      name: "Bamboo Gatherer (16 Bamboo)",
      item: "minecraft:bamboo",
      count: 16,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "paper_maker",
      name: "Paper Maker (8 Paper)",
      item: "minecraft:paper",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "sapling_collector",
      name: "Sapling Collector (4 Saplings, any type)",
      item: "minecraft:oak_sapling",
      count: 4,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "wheat_harvest",
      name: "Wheat Harvest (16 Wheat)",
      item: "minecraft:wheat",
      count: 16,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "potato_picker",
      name: "Potato Picker (8 Potatoes)",
      item: "minecraft:potato",
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "carrot_collector",
      name: "Carrot Collector (8 Carrots)",
      item: "minecraft:carrot",
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "beetroot_gatherer",
      name: "Beetroot Gatherer (8 Beetroots)",
      item: "minecraft:beetroot",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "pumpkin_harvest",
      name: "Pumpkin Harvest (2 Pumpkins)",
      item: "minecraft:pumpkin",
      count: 2,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "melon_slice_stack",
      name: "Melon Slice Stack (8 Melon Slices)",
      item: "minecraft:melon_slice",
      count: 8,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "vine_climber",
      name: "Vine Climber (8 Vines)",
      item: "minecraft:vine",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "lily_pad_collector",
      name: "Lily Pad Collector (4 Lily Pads)",
      item: "minecraft:lily_pad",
      count: 4,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "sweet_berries",
      name: "Sweet Berries (8 Sweet Berries)",
      item: "minecraft:sweet_berries",
      count: 8,
      points: 15,
      difficulty: "easy",
    },
    {
      id: "glow_berries",
      name: "Glow Berries (6 Glow Berries)",
      item: "minecraft:glow_berries",
      count: 6,
      points: 18,
      difficulty: "easy",
    },
    {
      id: "crafting_table_maker",
      name: "Crafting Table Maker (2 Crafting Tables)",
      item: "minecraft:crafting_table",
      count: 2,
      points: 10,
      difficulty: "easy",
    },
    {
      id: "chest_builder",
      name: "Chest Builder (2 Chests)",
      item: "minecraft:chest",
      count: 2,
      points: 12,
      difficulty: "easy",
    },
    {
      id: "fence_crafter",
      name: "Fence Crafter (16 Fences, any wood)",
      item: "minecraft:oak_fence",
      count: 16,
      points: 12,
      difficulty: "easy",
      variant: "any",
    },
    {
      id: "door_maker",
      name: "Door Maker (3 Doors, any wood)",
      item: "minecraft:oak_door",
      count: 3,
      points: 10,
      difficulty: "easy",
      variant: "any",
    },
  ],
  medium: [
    {
      id: "creepers_gift",
      name: "Creeper's Gift (4 Gunpowder)",
      item: "minecraft:gunpowder",
      count: 4,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "endermans_pearls",
      name: "Enderman's Pearls (3 Ender Pearls)",
      item: "minecraft:ender_pearl",
      count: 3,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "spiders_silk",
      name: "Spider's Silk (4 Spider Eyes)",
      item: "minecraft:spider_eye",
      count: 4,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "iron_forged",
      name: "Iron Forged (2 Iron Blocks)",
      item: "minecraft:iron_block",
      count: 2,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "diamond_toolsmith",
      name: "Diamond Toolsmith (1 Diamond Pickaxe)",
      item: "minecraft:diamond_pickaxe",
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "librarians_pride",
      name: "Librarian's Pride (4 Bookshelves)",
      item: "minecraft:bookshelf",
      count: 4,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "redstone_engineer",
      name: "Redstone Engineer (16 Redstone Dust)",
      item: "minecraft:redstone",
      count: 16,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "golden_ingots",
      name: "Golden Ingots (2 Gold Ingots)",
      item: "minecraft:gold_ingot",
      count: 2,
      points: 38,
      difficulty: "medium",
    },
    {
      id: "slime_hunter",
      name: "Slime Hunter (2 Slimeballs)",
      item: "minecraft:slime_ball",
      count: 2,
      points: 42,
      difficulty: "medium",
    },
    {
      id: "enchanters_start",
      name: "Enchanter's Start (1 Enchanting Table)",
      item: "minecraft:enchanting_table",
      count: 1,
      points: 45,
      difficulty: "medium",
    },
    {
      id: "treasure_map",
      name: "Treasure Map (1 Buried Treasure Map)",
      item: "minecraft:filled_map",
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "melon_merchant",
      name: "Melon Merchant (8 Melons)",
      item: "minecraft:melon_block",
      count: 8,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "pumpkin_patch",
      name: "Pumpkin Patch (4 Carved Pumpkins)",
      item: "minecraft:carved_pumpkin",
      count: 4,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "leather_worker",
      name: "Leather Worker (4 Leather)",
      item: "minecraft:leather",
      count: 4,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "phantom_membrane",
      name: "Phantom Membrane (1 Phantom Membrane)",
      item: "minecraft:phantom_membrane",
      count: 1,
      points: 45,
      difficulty: "medium",
    },
    {
      id: "cocoa_farmer",
      name: "Cocoa Farmer (8 Cocoa Beans)",
      item: "minecraft:cocoa_beans",
      count: 8,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "ink_sac_collector",
      name: "Ink Sac Collector (4 Ink Sacs)",
      item: "minecraft:ink_sac",
      count: 4,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "lapis_miner",
      name: "Lapis Miner (8 Lapis Lazuli)",
      item: "minecraft:lapis_lazuli",
      count: 8,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "dye_collection",
      name: "Dye Collection (6 Different Dyes)",
      item: "minecraft:red_dye",
      count: 6,
      points: 35,
      difficulty: "medium",
      variant: "any",
    },
    {
      id: "obsidian_harvest",
      name: "Obsidian Harvest (3 Obsidian)",
      item: "minecraft:obsidian",
      count: 3,
      points: 42,
      difficulty: "medium",
    },
    {
      id: "arrow_crafter",
      name: "Arrow Crafter (16 Arrows)",
      item: "minecraft:arrow",
      count: 16,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "prismarine_collector",
      name: "Prismarine Collector (8 Prismarine Shards)",
      item: "minecraft:prismarine_shard",
      count: 8,
      points: 38,
      difficulty: "medium",
    },
    {
      id: "rabbit_foot",
      name: "Rabbit Foot (1 Rabbit's Foot)",
      item: "minecraft:rabbit_foot",
      count: 1,
      points: 40,
      difficulty: "medium",
    },
    {
      id: "brick_maker",
      name: "Brick Maker (16 Bricks)",
      item: "minecraft:brick",
      count: 16,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "sugar_producer",
      name: "Sugar Producer (16 Sugar)",
      item: "minecraft:sugar",
      count: 16,
      points: 28,
      difficulty: "medium",
    },
    {
      id: "bowl_crafter",
      name: "Bowl Crafter (6 Bowls)",
      item: "minecraft:bowl",
      count: 6,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "glass_maker",
      name: "Glass Maker (16 Glass)",
      item: "minecraft:glass",
      count: 16,
      points: 30,
      difficulty: "medium",
    },
    {
      id: "dried_kelp_producer",
      name: "Dried Kelp Producer (16 Dried Kelp)",
      item: "minecraft:dried_kelp",
      count: 16,
      points: 32,
      difficulty: "medium",
    },
    {
      id: "honey_collector",
      name: "Honey Collector (2 Honey Bottles)",
      item: "minecraft:honey_bottle",
      count: 2,
      points: 35,
      difficulty: "medium",
    },
    {
      id: "honeycomb_gatherer",
      name: "Honeycomb Gatherer (3 Honeycombs)",
      item: "minecraft:honeycomb",
      count: 3,
      points: 35,
      difficulty: "medium",
    },
  ],
  hard: [
    {
      id: "enchanted_knowledge",
      name: "Enchanted Knowledge (1 Enchanted Book)",
      item: "minecraft:enchanted_book",
      count: 1,
      points: 55,
      difficulty: "hard",
      variant: "any",
    },
    {
      id: "golden_delicacy",
      name: "Golden Delicacy (1 Golden Apple)",
      item: "minecraft:golden_apple",
      count: 1,
      points: 60,
      difficulty: "hard",
    },
    {
      id: "village_vault",
      name: "Village Vault (8 Emeralds)",
      item: "minecraft:emerald",
      count: 8,
      points: 65,
      difficulty: "hard",
    },
    {
      id: "mob_tamer",
      name: "Mob Tamer (1 Name Tag)",
      item: "minecraft:name_tag",
      count: 1,
      points: 70,
      difficulty: "hard",
    },
    {
      id: "music_disc_hunter",
      name: "Music Disc Hunter (1 Music Disc, any)",
      item: "minecraft:music_disc_cat",
      count: 1,
      points: 65,
      difficulty: "hard",
      variant: "any",
    },
    {
      id: "diamond_fortune",
      name: "Diamond Fortune (3 Diamonds)",
      item: "minecraft:diamond",
      count: 3,
      points: 60,
      difficulty: "hard",
    },
    {
      id: "totem_raid",
      name: "Totem Raid (1 Totem of Undying)",
      item: "minecraft:totem_of_undying",
      count: 1,
      points: 75,
      difficulty: "hard",
    },
    {
      id: "horse_trader",
      name: "Horse Trader (1 Saddle)",
      item: "minecraft:saddle",
      count: 1,
      points: 55,
      difficulty: "hard",
    },
    {
      id: "oceans_heart",
      name: "Ocean's Heart (1 Heart of the Sea)",
      item: "minecraft:heart_of_the_sea",
      count: 1,
      points: 70,
      difficulty: "hard",
    },
    {
      id: "trident_bearer",
      name: "Trident Bearer (1 Trident)",
      item: "minecraft:trident",
      count: 1,
      points: 75,
      difficulty: "hard",
    },
    {
      id: "bell_ringer",
      name: "Bell Ringer (1 Bell)",
      item: "minecraft:bell",
      count: 1,
      points: 50,
      difficulty: "hard",
    },
    {
      id: "nautilus_shell",
      name: "Nautilus Shell (1 Nautilus Shell)",
      item: "minecraft:nautilus_shell",
      count: 1,
      points: 60,
      difficulty: "hard",
    },
  ],
};
