export const ANY_VARIANTS: Record<string, string[]> = {
  // Logs and wood
  "minecraft:oak_log": [
    "minecraft:oak_log",
    "minecraft:spruce_log",
    "minecraft:birch_log",
    "minecraft:jungle_log",
    "minecraft:acacia_log",
    "minecraft:dark_oak_log",
    "minecraft:mangrove_log",
    "minecraft:cherry_log",
    "minecraft:bamboo_block",
  ],
  // Planks
  "minecraft:oak_planks": [
    "minecraft:oak_planks",
    "minecraft:spruce_planks",
    "minecraft:birch_planks",
    "minecraft:jungle_planks",
    "minecraft:acacia_planks",
    "minecraft:dark_oak_planks",
    "minecraft:mangrove_planks",
    "minecraft:cherry_planks",
    "minecraft:bamboo_planks",
  ],
  // Wool
  "minecraft:white_wool": [
    "minecraft:white_wool",
    "minecraft:orange_wool",
    "minecraft:magenta_wool",
    "minecraft:light_blue_wool",
    "minecraft:yellow_wool",
    "minecraft:lime_wool",
    "minecraft:pink_wool",
    "minecraft:gray_wool",
    "minecraft:light_gray_wool",
    "minecraft:cyan_wool",
    "minecraft:purple_wool",
    "minecraft:blue_wool",
    "minecraft:brown_wool",
    "minecraft:green_wool",
    "minecraft:red_wool",
    "minecraft:black_wool",
  ],
  // Cooked meats / fish
  "minecraft:cooked_beef": [
    "minecraft:cooked_beef",
    "minecraft:cooked_mutton",
    "minecraft:cooked_chicken",
    "minecraft:cooked_porkchop",
    "minecraft:cooked_rabbit",
    "minecraft:cooked_cod",
    "minecraft:cooked_salmon",
  ],
  // Flowers
  "minecraft:poppy": [
    "minecraft:poppy",
    "minecraft:dandelion",
    "minecraft:blue_orchid",
    "minecraft:allium",
    "minecraft:azure_bluet",
    "minecraft:red_tulip",
    "minecraft:orange_tulip",
    "minecraft:pink_tulip",
    "minecraft:white_tulip",
    "minecraft:oxeye_daisy",
    "minecraft:cornflower",
    "minecraft:lily_of_the_valley",
    "minecraft:torchflower",
  ],
  // Dirt/Grass
  "minecraft:dirt": ["minecraft:dirt", "minecraft:grass_block"],
  // Enchanted book accepts any enchanted variant (still same id)
  "minecraft:enchanted_book": ["minecraft:enchanted_book"],
  // Music discs any disc
  "minecraft:music_disc_cat": [
    "minecraft:music_disc_11",
    "minecraft:music_disc_13",
    "minecraft:music_disc_blocks",
    "minecraft:music_disc_cat",
    "minecraft:music_disc_chirp",
    "minecraft:music_disc_far",
    "minecraft:music_disc_mall",
    "minecraft:music_disc_mellohi",
    "minecraft:music_disc_otherside",
    "minecraft:music_disc_pigstep",
    "minecraft:music_disc_relic",
    "minecraft:music_disc_stal",
    "minecraft:music_disc_strad",
    "minecraft:music_disc_wait",
    "minecraft:music_disc_ward",
  ],
};
