import { MinecraftItemTypes } from "@minecraft/vanilla-data";

export const ANY_VARIANTS: Record<string, string[]> = {
  // Logs and wood
  [MinecraftItemTypes.OakLog]: [
    MinecraftItemTypes.OakLog,
    MinecraftItemTypes.SpruceLog,
    MinecraftItemTypes.BirchLog,
    MinecraftItemTypes.JungleLog,
    MinecraftItemTypes.AcaciaLog,
    MinecraftItemTypes.DarkOakLog,
    MinecraftItemTypes.MangroveLog,
    MinecraftItemTypes.CherryLog,
    MinecraftItemTypes.BambooBlock,
  ],
  // Planks
  [MinecraftItemTypes.OakPlanks]: [
    MinecraftItemTypes.OakPlanks,
    MinecraftItemTypes.SprucePlanks,
    MinecraftItemTypes.BirchPlanks,
    MinecraftItemTypes.JunglePlanks,
    MinecraftItemTypes.AcaciaPlanks,
    MinecraftItemTypes.DarkOakPlanks,
    MinecraftItemTypes.MangrovePlanks,
    MinecraftItemTypes.CherryPlanks,
    MinecraftItemTypes.BambooPlanks,
  ],
  // Wool
  [MinecraftItemTypes.WhiteWool]: [
    MinecraftItemTypes.WhiteWool,
    MinecraftItemTypes.OrangeWool,
    MinecraftItemTypes.MagentaWool,
    MinecraftItemTypes.LightBlueWool,
    MinecraftItemTypes.YellowWool,
    MinecraftItemTypes.LimeWool,
    MinecraftItemTypes.PinkWool,
    MinecraftItemTypes.GrayWool,
    MinecraftItemTypes.LightGrayWool,
    MinecraftItemTypes.CyanWool,
    MinecraftItemTypes.PurpleWool,
    MinecraftItemTypes.BlueWool,
    MinecraftItemTypes.BrownWool,
    MinecraftItemTypes.GreenWool,
    MinecraftItemTypes.RedWool,
    MinecraftItemTypes.BlackWool,
  ],
  // Cooked meats / fish
  [MinecraftItemTypes.CookedBeef]: [
    MinecraftItemTypes.CookedBeef,
    MinecraftItemTypes.CookedMutton,
    MinecraftItemTypes.CookedChicken,
    MinecraftItemTypes.CookedPorkchop,
    MinecraftItemTypes.CookedRabbit,
    MinecraftItemTypes.CookedCod,
    MinecraftItemTypes.CookedSalmon,
  ],
  // Mushrooms
  [MinecraftItemTypes.RedMushroom]: [MinecraftItemTypes.RedMushroom, MinecraftItemTypes.BrownMushroom],
  // Flowers
  [MinecraftItemTypes.Poppy]: [
    MinecraftItemTypes.Poppy,
    MinecraftItemTypes.Dandelion,
    MinecraftItemTypes.BlueOrchid,
    MinecraftItemTypes.Allium,
    MinecraftItemTypes.AzureBluet,
    MinecraftItemTypes.RedTulip,
    MinecraftItemTypes.OrangeTulip,
    MinecraftItemTypes.PinkTulip,
    MinecraftItemTypes.WhiteTulip,
    MinecraftItemTypes.OxeyeDaisy,
    MinecraftItemTypes.Cornflower,
    MinecraftItemTypes.LilyOfTheValley,
    MinecraftItemTypes.Torchflower,
  ],
  // Dirt/Grass
  [MinecraftItemTypes.Dirt]: [MinecraftItemTypes.Dirt, MinecraftItemTypes.GrassBlock],
  // Saplings
  [MinecraftItemTypes.OakSapling]: [
    MinecraftItemTypes.OakSapling,
    MinecraftItemTypes.SpruceSapling,
    MinecraftItemTypes.BirchSapling,
    MinecraftItemTypes.JungleSapling,
    MinecraftItemTypes.AcaciaSapling,
    MinecraftItemTypes.DarkOakSapling,
    MinecraftItemTypes.MangrovePropagule,
    MinecraftItemTypes.CherrySapling,
  ],
  // Fences
  [MinecraftItemTypes.OakFence]: [
    MinecraftItemTypes.OakFence,
    MinecraftItemTypes.SpruceFence,
    MinecraftItemTypes.BirchFence,
    MinecraftItemTypes.JungleFence,
    MinecraftItemTypes.AcaciaFence,
    MinecraftItemTypes.DarkOakFence,
    MinecraftItemTypes.MangroveFence,
    MinecraftItemTypes.CherryFence,
    MinecraftItemTypes.BambooFence,
    MinecraftItemTypes.CrimsonFence,
    MinecraftItemTypes.WarpedFence,
  ],
  // Doors
  [MinecraftItemTypes.AcaciaDoor]: [
    MinecraftItemTypes.OakDoor,
    MinecraftItemTypes.SpruceDoor,
    MinecraftItemTypes.BirchDoor,
    MinecraftItemTypes.JungleDoor,
    MinecraftItemTypes.AcaciaDoor,
    MinecraftItemTypes.DarkOakDoor,
    MinecraftItemTypes.MangroveDoor,
    MinecraftItemTypes.CherryDoor,
    MinecraftItemTypes.BambooDoor,
    MinecraftItemTypes.CrimsonDoor,
    MinecraftItemTypes.WarpedDoor,
  ],
  // Dyes
  [MinecraftItemTypes.RedDye]: [
    MinecraftItemTypes.WhiteDye,
    MinecraftItemTypes.LightGrayDye,
    MinecraftItemTypes.GrayDye,
    MinecraftItemTypes.BlackDye,
    MinecraftItemTypes.BrownDye,
    MinecraftItemTypes.RedDye,
    MinecraftItemTypes.OrangeDye,
    MinecraftItemTypes.YellowDye,
    MinecraftItemTypes.LimeDye,
    MinecraftItemTypes.GreenDye,
    MinecraftItemTypes.CyanDye,
    MinecraftItemTypes.LightBlueDye,
    MinecraftItemTypes.BlueDye,
    MinecraftItemTypes.PurpleDye,
    MinecraftItemTypes.MagentaDye,
    MinecraftItemTypes.PinkDye,
  ],
  // Music discs any disc
  [MinecraftItemTypes.MusicDiscCat]: [
    MinecraftItemTypes.MusicDisc11,
    MinecraftItemTypes.MusicDisc13,
    MinecraftItemTypes.MusicDiscBlocks,
    MinecraftItemTypes.MusicDiscCat,
    MinecraftItemTypes.MusicDiscChirp,
    MinecraftItemTypes.MusicDiscFar,
    MinecraftItemTypes.MusicDiscMall,
    MinecraftItemTypes.MusicDiscMellohi,
    MinecraftItemTypes.MusicDiscOtherside,
    MinecraftItemTypes.MusicDiscPigstep,
    MinecraftItemTypes.MusicDiscRelic,
    MinecraftItemTypes.MusicDiscStal,
    MinecraftItemTypes.MusicDiscStrad,
    MinecraftItemTypes.MusicDiscWait,
    MinecraftItemTypes.MusicDiscWard,
  ],
};
